import { useEffect, useState, useRef } from 'react'
import './App.css'

const products = [
  ['Doble Cheese Burger','hamburguesa',45,'Doble carne de res artesanal, doble queso cheddar fundido, lechuga fresca, tomate y nuestra salsa secreta.','1568901346375-23c9450c58cd'],['Hamburguesa Clásica','hamburguesa',35,'Carne de res a la parrilla, queso americano, lechuga, tomate, cebolla morada y pepinillos.','1550547660-d9450f859349'],['Bacon BBQ Burger','hamburguesa',48,'Carne de res, tocino ahumado, aros de cebolla, queso cheddar y salsa BBQ.','1586190848861-99aa4a171e90'],['Veggie Burger','hamburguesa',38,'Medallón de garbanzos y lentejas, palta, espinaca, tomate y mayonesa vegana.','1525059696034-4967a8e1dca2'],['Chicken Crispy','hamburguesa',40,'Pechuga de pollo frita extracrujiente, ensalada de col y mayonesa picante.','1625813506062-0aeb1d7a094b'],['Combo Bacon BBQ','combo',62,'Bacon BBQ Burger, papas fritas medianas y gaseosa helada de 500 ml.','1551782450-17144efb9c50'],['Combo Doble Cheese','combo',58,'Doble Cheese Burger, papas grandes con cheddar y bebida a elección.','1568901346375-23c9450c58cd'],['Teriyaki Burger','hamburguesa',44,'Carne de res marinada, piña asada, mozzarella y glaseado teriyaki.','1586190848861-99aa4a171e90']
].map(([name,category,price,description,id])=>({name,category,price,description,image:`https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=800&q=80`}))
const extras=[{name:'Doble Queso',price:5},{name:'Tocino Adicional',price:8},{name:'Carne Extra',price:12}]
const money=n=>`Bs. ${n.toFixed(2)}`

export default function App(){
 const [route,setRoute]=useState(()=>location.hash.slice(1)||'inicio'),[dark,setDark]=useState(false),[mobile,setMobile]=useState(false),[cart,setCart]=useState([]),[drawer,setDrawer]=useState(false),[modal,setModal]=useState(null),[toast,setToast]=useState(null),[chosen,setChosen]=useState(null),[filter,setFilter]=useState('all'),[qty,setQty]=useState(1),[addOns,setAddOns]=useState([]),[user,setUser]=useState(()=>{try{return JSON.parse(localStorage.getItem('burgerhausUser'))}catch{return null}})
 useEffect(()=>{const h=()=>setRoute(location.hash.slice(1)||'inicio');addEventListener('hashchange',h);return()=>removeEventListener('hashchange',h)},[]);useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(null),3000);return()=>clearTimeout(t)},[toast])
 const nav=p=>{location.hash=p;setMobile(false);scrollTo({top:0,behavior:'smooth'})},notify=(message,error=false)=>setToast({message,error}),add=(p,n=1,adds=[])=>{const name=p.name+(adds.length?` (+ ${adds.map(x=>x.name).join(', ')})`:''),price=p.price+adds.reduce((s,x)=>s+x.price,0);setCart(c=>{const old=c.find(x=>x.name===name);return old?c.map(x=>x===old?{...x,quantity:x.quantity+n}:x):[...c,{name,price,quantity:n}]})},openInfo=p=>{setChosen(p);setQty(1);setAddOns([]);setModal('info')},items=cart.reduce((s,x)=>s+x.quantity,0),subtotal=cart.reduce((s,x)=>s+x.price*x.quantity,0)
 const signIn=(form)=>{const data=new FormData(form),email=data.get('email'),nextUser={name:data.get('name')||String(email).split('@')[0],email};localStorage.setItem('burgerhausUser',JSON.stringify(nextUser));setUser(nextUser);notify('¡Sesión iniciada con éxito!')}
 const shared={nav,add,openInfo,notify,qty,setQty,addOns,setAddOns}
 let content=route==='inicio'?<Home filter={filter} setFilter={setFilter} {...shared}/>:route.startsWith('menu/')?<Category category={route.split('/')[1]} {...shared}/>:route==='detalle'?<Detail product={chosen||products[0]} {...shared}/>:route==='contacto'?<Contact notify={notify}/>:route==='rastreo'?<Tracking/>:route==='login'?<Auth nav={nav} signIn={signIn}/>:<Home filter={filter} setFilter={setFilter} {...shared}/>
 return <div className={dark?'app dark':'app'}><Header {...{nav,dark,setDark,mobile,setMobile,items,setDrawer,setModal,user}}/>{content}<Footer nav={nav}/>{toast&&<div className={`toast ${toast.error?'error':''}`}>{toast.message}</div>}{drawer&&<Cart {...{cart,subtotal,setCart,setDrawer,setModal,notify}}/>}{modal==='info'&&<Info {...{chosen,qty,setQty,addOns,setAddOns,add,setModal,notify}}/>}{modal==='checkout'&&<Checkout close={()=>setModal(null)} submit={e=>{e.preventDefault();if(!cart.length)return notify('¡Error: el carrito está vacío!',true);setCart([]);setDrawer(false);setModal('confirm');notify('¡Compra exitosa! Gracias por tu pedido.')}}/>}{modal==='confirm'&&<Confirm close={()=>setModal(null)} nav={nav}/>} {modal==='login'&&<Login close={()=>setModal(null)} nav={nav} signIn={signIn}/>}</div>
}
function Header({nav,dark,setDark,mobile,setMobile,items,setDrawer,setModal,user}){return <header className="header"><div className="container bar"><button className="logo" onClick={()=>nav('inicio')}>Burgerhaus & Café</button><nav className={mobile?'nav active':'nav'}><button onClick={()=>nav('inicio')}>Inicio</button><button onClick={()=>nav('inicio')}>Menú</button><button onClick={()=>nav('rastreo')}>Rastrear Pedido</button><button onClick={()=>nav('contacto')}>Contacto</button></nav><div className="actions"><button className="login" onClick={()=>user?alert(`Sesión activa: ${user.email}`):setModal('login')}>{user?`Hola, ${user.name}`:'Iniciar Sesión'}</button><button className="icon" onClick={()=>setDark(!dark)} aria-label="Cambiar tema">{dark?'☀':'☾'}</button><button className="icon cart" onClick={()=>setDrawer(true)} aria-label="Abrir carrito">🛒<span>{items}</span></button><button className="hamb" onClick={()=>setMobile(!mobile)} aria-label="Menú">☰</button></div></div></header>}
function Home({filter,setFilter,...p}){const menuRef=useRef(null);let shown=filter==='all'?products:products.filter(x=>x.category===filter);const scroll=()=>menuRef.current?.scrollIntoView({behavior:'smooth'});return <main><section className="hero"><div><h1>El Arte de la Hamburguesa Artesanal</h1><p>Donde cada ingrediente cuenta una historia de sabor y calidad.</p><button className="btn primary" onClick={scroll}>Ver Menú</button><button className="btn outline" onClick={scroll}>Ordenar Ahora</button></div></section><section ref={menuRef} id="menu" className="section container"><h2>Nuestro Menú</h2><Filters value={filter} change={setFilter}/><Cards products={shown} {...p}/></section></main>}
function Filters({value,change}){return <div className="filters">{[['all','Todo'],['hamburguesa','Hamburguesas'],['combo','Combos']].map(x=><button key={x[0]} className={value===x[0]?'active':''} onClick={()=>change(x[0])}>{x[1]}</button>)}</div>}
function Cards({products,add,openInfo,notify}){return <div className="grid">{products.map(p=><article className="card" key={p.name}><img src={p.image} alt={p.name}/><h3>{p.name}</h3><b>{money(p.price)}</b><div><button className="btn secondary" onClick={()=>openInfo(p)}>Info</button><button className="btn primary" onClick={()=>{add(p);notify(`¡${p.name} añadido al carrito!`)}}>Añadir</button></div></article>)}</div>}
function Category({category,...p}){let title='Nuestras Hamburguesas',list=products.filter(x=>x.category==='hamburguesa');if(category==='combos'){title='Nuestros Combos';list=products.filter(x=>x.category==='combo')}if(category==='bebidas'){title='Nuestras Bebidas & Café';list=[{...products[0],name:'Coca-Cola',price:15},{...products[1],name:'Café Americano',price:12}]}if(category==='acompanamientos'){title='Nuestros Acompañamientos';list=[{...products[0],name:'Papas Fritas',price:18},{...products[1],name:'Aros de Cebolla',price:20}]}return <main className="page"><section className="section container"><h1>{title}</h1><Cards products={list} {...p}/></section></main>}
function Detail({product,qty,setQty,add,notify}){const [adds,setAdds]=useState([]),unit=product.price+adds.reduce((s,x)=>s+x.price,0);return <main className="page"><section className="detail container"><img src={product.image} alt={product.name}/><div><h1>{product.name}</h1><p>{product.description}</p><strong>{money(unit*qty)}</strong><Extras value={adds} change={setAdds}/><div className="detailactions"><Quantity value={qty} change={setQty}/><button className="btn primary" onClick={()=>{add(product,qty,adds);notify(`¡${product.name} añadido al pedido!`)}}>Añadir al Pedido</button></div></div></section></main>}
function Extras({value,change}){return <div className="extras"><h3>Personaliza tu Hamburguesa</h3>{extras.map(x=><label key={x.name}><input type="checkbox" checked={value.some(y=>y.name===x.name)} onChange={e=>change(e.target.checked?[...value,x]:value.filter(y=>y.name!==x.name))}/> {x.name} (+ {money(x.price)})</label>)}</div>};function Quantity({value,change}){return <div className="quantity"><button onClick={()=>change(Math.max(1,value-1))}>−</button><span>{value}</span><button onClick={()=>change(value+1)}>+</button></div>}
function Cart({cart,subtotal,setCart,setDrawer,setModal,notify}){const change=(i,d)=>setCart(c=>c.flatMap((x,n)=>n!==i?[x]:x.quantity+d>0?[{...x,quantity:x.quantity+d}]:[]));const checkout=()=>cart.length?(setDrawer(false),setModal('checkout')):notify('¡Error: el carrito está vacío!',true);return <aside className="drawer"><header><h2>Tu Pedido</h2><button onClick={()=>setDrawer(false)}>×</button></header><div>{cart.length?cart.map((x,i)=><article className="cartitem" key={x.name}><p><b>{x.name}</b><strong>{money(x.price*x.quantity)}</strong></p><div><button onClick={()=>change(i,-1)}>−</button><span>{x.quantity}</span><button onClick={()=>change(i,1)}>+</button><button className="remove" onClick={()=>change(i,-x.quantity)}>×</button></div></article>):<p>Tu carrito está vacío.</p>}</div><footer><p>Subtotal <b>{money(subtotal)}</b></p><p>Envío <b>{money(15)}</b></p><h3>Total <b>{money(cart.length?subtotal+15:0)}</b></h3><button className="btn primary" onClick={checkout}>Proceder al Pago</button></footer></aside>}
function Modal({close,children}){return <div className="backdrop"><section className="modal"><button className="close" onClick={close}>×</button>{children}</section></div>};function Field({label,...rest}){return <label className="field">{label}<input {...rest}/></label>}
function Info({chosen,qty,setQty,addOns,setAddOns,add,setModal,notify}){let price=(chosen.price+addOns.reduce((s,x)=>s+x.price,0))*qty;return <Modal close={()=>setModal(null)}><h2>{chosen.name}</h2><p>{chosen.description}</p><Extras value={addOns} change={setAddOns}/><Quantity value={qty} change={setQty}/><button className="btn primary full" onClick={()=>{add(chosen,qty,addOns);setModal(null);notify(`¡${chosen.name} añadido al pedido!`)}}>Añadir al Pedido ({money(price)})</button></Modal>}
function Checkout({close,submit}){return <Modal close={close}><h2>Finalizar Compra</h2><form onSubmit={submit}><Field label="Nombre Completo *" name="name" required/><Field label="Teléfono *" name="phone" required type="tel"/><Field label="Dirección de Envío *" name="address" required/><button className="btn primary full">Confirmar Pedido</button></form></Modal>};function Confirm({close,nav}){const [code]=useState(()=>Math.floor(1000+Math.random()*9000));return <Modal close={close}><div className="center"><h2>¡Pedido Confirmado!</h2><p>Código de tu pedido:</p><strong className="code">#{code}</strong><p>Tiempo de preparación: <b>15 - 20 min</b></p><p>Entrega estimada: <b>30 - 45 min</b></p><button className="btn primary full" onClick={()=>{close();nav('rastreo')}}>Rastrear pedido</button></div></Modal>}
function Login({close,nav,signIn}){return <Modal close={close}><h2>Iniciar Sesión</h2><form onSubmit={e=>{e.preventDefault();signIn(e.currentTarget);close();nav('inicio')}}><Field label="Correo electrónico *" name="email" type="email" required/><Field label="Contraseña *" name="password" type="password" required/><button className="btn primary full">Entrar</button></form></Modal>}
function Auth({nav,signIn}){const [register,setRegister]=useState(false);return <main className="auth"><section><div className="tabs"><button className={!register?'active':''} onClick={()=>setRegister(false)}>Iniciar Sesión</button><button className={register?'active':''} onClick={()=>setRegister(true)}>Crear Cuenta</button></div><form onSubmit={e=>{e.preventDefault();signIn(e.currentTarget);nav('inicio')}}>{register&&<Field label="Nombre completo" name="name" required/>}<Field label="Correo electrónico" name="email" type="email" required/><Field label="Contraseña" type="password" required/><button className="btn primary full">{register?'Registrarse':'Ingresar'}</button></form></section></main>}
function Contact({notify}){const [file,setFile]=useState('');return <main className="contact"><section><i>☏</i><h1>How can we help?</h1><p>Tell us what happened and our support team will take a look.</p><form onSubmit={e=>{e.preventDefault();e.currentTarget.reset();setFile('');notify('Thanks! Your report has been submitted.')}}><label className="field">What happened?<select required defaultValue=""><option value="" disabled>Select an issue...</option><option>Something went wrong with my order</option><option>My delivery is late</option><option>I have a payment question</option></select></label><label className="field">Description<textarea required rows="5" placeholder="Please provide details about the issue..."/></label><label className="upload">📷 <b>Upload a file</b><small>PNG, JPG, GIF up to 5MB</small><input type="file" accept="image/png,image/jpeg,image/gif" onChange={e=>{let f=e.target.files[0];if(f?.size>5242880){setFile('The file is larger than 5MB.');e.target.value=''}else setFile(f?.name||'')}}/></label><small>{file}</small><button className="btn primary full">Submit Report ▷</button></form></section></main>}
function Tracking(){const [seconds,setSeconds]=useState(860),[order,setOrder]=useState('1024'),[lookup,setLookup]=useState('');useEffect(()=>{let t=setInterval(()=>setSeconds(n=>Math.max(0,n-1)),1000);return()=>clearInterval(t)},[]);let time=`${String(Math.floor(seconds/60)).padStart(2,'0')} : ${String(seconds%60).padStart(2,'0')}`;return <main className="track"><section><div className="trackhead"><div><p>Seguimiento en vivo</p><h1>Order <span>#{order}</span></h1><p>Tu pedido está avanzando. Te avisaremos cuando esté en camino.</p></div><aside>Tiempo estimado<strong>{time}</strong></aside></div><article className="status"><b>● Preparing your order</b><div>{['✓ Order Received','♨ Preparing','➜ On the Way','⌂ Delivered'].map((x,i)=><span className={i<2?'done':''} key={x}>{x}</span>)}</div></article><div className="orders"><article><h2>Order Summary</h2><p>The Haus Double <b>Bs. 90.00</b></p><p>Curly Fries <b>Bs. 35.00</b></p><p>Coca-Cola <b>Bs. 15.00</b></p><h3>Total <b>Bs. 154.00</b></h3></article><div><article><h2>Customer Info</h2><p>Valentina Sabrina</p><a href="mailto:valentina@example.com">valentina@example.com</a></article><article><h2>Delivery Address</h2><p>Av. Principal #1024, Zona Norte</p><span>Santa Cruz de la Sierra, Bolivia</span></article><form className="lookup" onSubmit={e=>{e.preventDefault();if(lookup)setOrder(lookup)}}><label>¿Buscas otro pedido?</label><div><input value={lookup} onChange={e=>setLookup(e.target.value)} placeholder="Order number"/><button className="btn primary">Consultar</button></div></form></div></div></section></main>}
function Footer({nav}){return <footer className="footer"><div className="container"><section><h3>Burgerhaus & Café</h3><p>Horario: Lun - Dom, 12:00pm - 11:00pm</p></section><section><h4>NAVEGACIÓN</h4><button onClick={()=>nav('inicio')}>Inicio</button><button onClick={()=>nav('contacto')}>Contacto</button></section><section><h4>SÍGUENOS</h4><p>f &nbsp; ◎ &nbsp; 𝕏</p></section></div><p>© 2026 Burgerhaus & Café. Todos los derechos reservados.</p></footer>}
